### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by krugar**
hey,

there were some minor syntax glitches (mostly in index.php) that i've fixed while catching up to your branch. i'll update this or PR again if i find anything else

i'm pretty impressed by what you've made :)

### CODE REVIEW

**Comment by tzeumer** [comment]
Oops, thanks. :)

But there is no need for curl anymore - I think I removed it everywhere a while ago already ;)

**Comment by krugar** [comment]
yea, sorry for letting that slip into the PR, noticed that too late

**Comment by krugar** [comment]
guess we can close this, right?

btw, i would like to create a 0.4 release branch soonish, do you have any features in the works that you want to have in the next version or would this be an opportune time for you as well?

**Comment by tzeumer** [comment]
I'm very ok with a new release. Certainly everything is not perfect, but I think there are no major bugs anymore. My time is somewhat limited in the near future anyway. 

What is the status of you Endnote citation export? We still show the demo output and the Endnote attachment option is visible but disabled. If it can't be finished, it should at least be hidden in a release version.

Just curious - you are still using version 0.3 in your location?

**Comment by krugar** [comment]
yep, still 0.3 here, been doing other stuff lately.

i haven't touched the export, will disable the visuals when bundling 0.4.

**Pull request closed without merging**
